version: '3.9'

volumes:
  clickhouse-data:

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=retroced
      - MYSQL_ROOT_PASSWORD=retroced
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d/
      - ./db/config/my.cnf:/etc/mysql/my.cnf
  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
        - 9000:9000
        - 8123:8123
  service:
    build: .
    ports:
      - 8080:8080


